services:
  - type: web
    name: smartjobai-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: smartjobai-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: smartjobai-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: smartjobai-db
          property: password

databases:
  - name: smartjobai-db
    databaseName: smartjobai_db
    user: smartjobuser
