spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartjobai
    username: postgres
    password: postgres
  jpa:
    show-sql: true

app:
  jwt:
    secret: dev-secret-troque-antes-de-ir-para-producao-0123456789

logging:
  level:
    com.smartjobai: DEBUG
    org.hibernate.SQL: DEBUG
